### ISSUE TITLE
Dataset_ID: HakaiCTDProvisional

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#1]
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [ ] Raw Data Submission
- [ ] CIOOS Metadata Form 

## ERDDAP Dataset Creation (Data Integrator)
- Dataset Transformation 
    - [ ] :green_circle: Directly Compatible
    - [x] :yellow_circle: Minor Revisions
    - [ ] :orange_circle: Major Revisions
    - [ ] :red_circle:  Incompatible/Missing Information
- [x] Near Real-time Data Integration 
- [] QARTOD Integration 
- [x] ERDDAP Integration 
- [x] ERDDAP Dataset Documentation 
- [ ] ERDDAP Test Locally 
- [ ] Add Dataset to Development Branch
## Dataset Review (Data Administrator)
Dataset Development Branch Revision 
- [ ] :green_circle: Approved
- [ ] :yellow_circle: Minor Revisions
- [ ] :orange_circle: Major Revisions

## Dataset Completion (Data Integrator)
- [ ] Merge Development Dataset to Production Branch 
- [ ] COMPLETED

**Comment by trollpete** [comment]
Would I just quote in the reply to update?

**Comment by n-a-t-e** [comment]
@trollpete  you have write access now so if you wanted to you could check the boxes or edit the issue, or can comment

**Comment by JessyBarrette** [comment]
I'm gonna try to change the boxes so that the progress bar  is representative the real progress by omitting the optional boxes.

**Comment by trollpete** [comment]
There we go - thanks - didn't see the edit option before. Looks great to me.

**Comment by JessyBarrette** [comment]
We may not have to use any other tools, the issue page will show the progress of each issue with that
https://github.com/HakaiInstitute/hakai-datasets/issues

**Comment by raytula** [comment]
> We may not have to use any other tools, the issue page will show the progress of each issue with that
> https://github.com/HakaiInstitute/hakai-datasets/issues

Yeah, it's handy to see how many tasks are complete from the main issue list.

![image](https://user-images.githubusercontent.com/3999893/106670458-0e494e00-657b-11eb-813e-eb1756188b01.png)

I like what I'm seeing so far.

For TulaSalud we may use milestones quite a bit to associate a bunch of issues with a monthly release.  Not sure if/how that would be helpful here.  It may be helpful to have regular/scheduled _releases_ that include one or more datasets.  @pramod-thupaki and I have been talking a bit about that, in the context of CIOOS and the various CIOOS datasets that are currently on the dev server.  In fact, just today Di Wan was asking about if/when we can get some of those datasets moved to the CIOOS production system.
