### ISSUE TITLE
Dataset Submission: HakaiKCBuoyResearch

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#10]
# Hakai Dataset Submission 
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [x] Original Data Submission
- [x] CIOOS Metadata Form completed

## ERDDAP Dataset Creation (Data Integrator)
- [x] Dataset Transformation  (Format label)
    - :green_circle: Format Compatible 
    - :yellow_circle: Format Minor Revisions
    - :orange_circle: Format Major Revisions
    - :red_circle:  Format Incompatible/Missing Information
- [x] Near Real-time Data Integration 
- [x] QARTOD Integration 
- [x] ERDDAP Integration 
- [x] ERDDAP Dataset Documentation 
- [x] ERDDAP Test Locally 
- [x] Add Dataset to Development Branch

## Dataset Review (Data Administrator)
Here's the finalized dataset to present to the data administrator:
- [dev ERDDAP](https://goose.hakai.org/erddap/tabledap/HakaiKCBuoyResearch.html) (there's an issue with the mooring_name variable, to review)
- [dev CKAN](https://pac-dev1.cioos.org/ckan/dataset/ca-coos_8b069feb-57fc-4d57-bf5c-761fd7cf0b45)
- [CIOOS Metadata](https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-MVOU3K945DDk7-D-ZfE)

- [x] Dataset Development Branch Revision (Reviewer Label)
    - :green_circle: Reviewer Approved
    - :yellow_circle: Reviewer Minor Revisions    
    - :orange_circle: Reviewer Major Revisions

## Dataset Completion (Data Integrator)
- [x] Merge Development Dataset to Production Branch 
- [x] COMPLETED

**Comment by JessyBarrette** [comment]
CKAN record available here on pac-dev1
https://pac-dev1.cioos.org/ckan/dataset/ca-coos_94f9cbdb-33a1-4c0b-a72d-8157a7dfdd20

**Comment by JessyBarrette** [comment]
The development dataset is now available on the hakai development erddap server:
https://goose.hakai.org/erddap/tabledap/HakaiKCBuoyResearch.html

**Comment by JessyBarrette** [comment]
@n-a-t-e  Looks like there's some encoding issues between the metadata form and the CKAN record:
![image](https://user-images.githubusercontent.com/30420025/110386459-29ddc380-8015-11eb-8e5c-e8e7c75bf506.png)

**Comment by JessyBarrette** [comment]
@raytula documentation was replaced by a link to the NCEI dataset. I also saw that newer data was available on NCEI and updated the ERDDAP record with the newest data. Changes should be reflected on CKAN soon

**Comment by raytula** [comment]
Thanks @JessyBarrette .  As noted in #9, Hakai should likely show up as a responsible party.  I see that this issue is where you pinged Nate about the potential encoding issue.

**Comment by JessyBarrette** [comment]
Here's the finalized dataset to present to the data administrator:
- dev ERDDAP (correct character issue)
- [dev CKAN](https://pac-dev1.cioos.org/ckan/dataset/ca-coos_8b069feb-57fc-4d57-bf5c-761fd7cf0b45)
- [CIOOS Metadata](https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/review/hM2aN3v9MzZ6J4KGMOEW2s9gidj2/-MVOU3K945DDk7-D-ZfE)

**Comment by raytula** [comment]
Thanks @JessyBarrette .  The CIOOS metadata link is linking to 'Not found'

**Comment by JessyBarrette** [comment]
@raytula updated!

**Comment by JessyBarrette** [comment]
This dataset is now available online. We can close that issue!
