### ISSUE TITLE
Dataset Submission: HakaiColumbiaFerryResearch

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#11]
# Hakai Dataset Submission 
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [x] Original Data Submission
- [x] CIOOS Metadata Form completed

## ERDDAP Dataset Creation (Data Integrator)
- [x] Dataset Transformation  (Format label)
    - :green_circle: Format Compatible 
    - :yellow_circle: Format Minor Revisions
    - :orange_circle: Format Major Revisions
    - :red_circle:  Format Incompatible/Missing Information
- [x] Near Real-time Data Integration 
- [x] QARTOD Integration 
- [x] ERDDAP Integration 
- [x] ERDDAP Dataset Documentation 
- [x] ERDDAP Test Locally 
- [x] Add Dataset to Development Branch

## Dataset Review (Data Administrator)
Finalized Datasets for presentation to the data administrator:
- [dev ERDDAP](https://goose.hakai.org/erddap/tabledap/HakaiColumbiaFerryResearch.html)
- [dev CKAN](https://pac-dev1.cioos.org/ckan/dataset/ca-coos_dd325fc4-033c-4696-b38d-0ac883ad67eb)
- [CIOOS Metadata](https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-MVOS5S_ZuOIGii40F_6)

- [x] Dataset Development Branch Revision (Reviewer Label)
    - :green_circle: Reviewer Approved
    - :yellow_circle: Reviewer Minor Revisions    
    - :orange_circle: Reviewer Major Revisions

## Dataset Completion (Data Integrator)
- [x] Merge Development Dataset to Production Branch 
- [x] COMPLETED

**Comment by JessyBarrette** [comment]
Metadata record is available on the pac-dev ckan sever:
https://pac-dev1.cioos.org/ckan/dataset/7c86496d-86d0-4093-823a-b6d47696f5ba

**Comment by JessyBarrette** [comment]
The development dataset is now available on the hakai development erddap server:
https://goose.hakai.org/erddap/tabledap/HakaiColumbiaFerryResearch.html

**Comment by JessyBarrette** [comment]
Original documents were replaced by a link to the NCEI repo of this dataset:
https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/review/hM2aN3v9MzZ6J4KGMOEW2s9gidj2/-MLo1Lxdzl-2CHjZgmeZ

**Comment by JessyBarrette** [comment]
Finalized Datasets for presentation to the data administrator:
- ERDDAP: https://goose.hakai.org/erddap/tabledap/HakaiColumbiaFerryResearch.html
- CKAN: https://pac-dev1.cioos.org/ckan/dataset/ca-coos_dd325fc4-033c-4696-b38d-0ac883ad67eb

**Comment by raytula** [comment]
Thanks @JessyBarrette .  The CIOOS metadata link is linking to 'Not found'

**Comment by JessyBarrette** [comment]
@raytula updated!

**Comment by JessyBarrette** [comment]
This dataset is now available online. We can close that issue!
