### ISSUE TITLE
Dataset Submission: HakaiADCPTimeSeriesProvisional

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#12]
# Hakai Dataset Submission 
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [x] Original Data Submission
- [x] CIOOS Metadata Form completed

## ERDDAP Dataset Creation (Data Integrator)
- [x] Dataset Transformation  (Format label)
    - :green_circle: Format Compatible 
    - :yellow_circle: Format Minor Revisions
    - :orange_circle: Format Major Revisions
    - :red_circle:  Format Incompatible/Missing Information
- [x] Near Real-time Data Integration 
- [x] QARTOD Integration 
- [x] ERDDAP Integration 
- [x] ERDDAP Dataset Documentation 
- [x] ERDDAP Test Locally 
- [x] Add Dataset to Development Branch

## Dataset Review (Data Administrator)
[CIOOS Metadata Form](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-MsbCMOYj2L_7dgICnzw)
[ERDDAP development](https://goose.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.html)
- [x] Dataset Development Branch Revision (Reviewer Label)
    - :green_circle: Reviewer Approved
    - :yellow_circle: Reviewer Minor Revisions    
    - :orange_circle: Reviewer Major Revisions

## Dataset Completion (Data Integrator)
- [x] Merge Development Dataset to Production Branch 
- [x] COMPLETED

**Comment by JessyBarrette** [comment]
A small minor implementation of the zero surface pressure is needed before moving ahead with this dataset. 

Once happy with it, we will ask review from someone at IOS potentially.

**Comment by JessyBarrette** [comment]
Dataset is available on the development ERDDAP
https://goose.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.html

**Comment by JessyBarrette** [comment]
It was decided to move this dataset to a provisional type.

**Comment by JessyBarrette** [comment]
CIOOS metadata form is now available at https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-MsbCMOYj2L_7dgICnzw

**Comment by JessyBarrette** [comment]
Hi @pramod-thupaki,
In order to officially release the Hakai ADCP Timeseries Dataset, I would need someone to review the ERDDAP dataset itself [here](https://goose.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.html) and its associated CKAN record [here](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-MsbCMOYj2L_7dgICnzw). 

The dataset is automatically generated by using the same packaged developed at IOS with a few more changes to it.

Let me know your thoughts, 
Jessy

**Comment by pramod-thupaki** [comment]
Looks good. Just a couple of minor changes. I will email you the suggested edits.

**Comment by JessyBarrette** [comment]
@pramod-thupaki  suggested the following changes to the metadata form:

> 2 - Can we modify the title to indicate location(s) and when (month & year) ? (Central Coast BC)
> 3 - Indicate station names /location names in description to help searches on catalog work more efficiently

Right now this dataset regroups all the ADCP data collected by Hakai, which is the following projects:
1. Quadra ADCP Initial Test Deployment
2. Calvert ADCP deployment in Kwakshua
3. UVic/Hakai ADCP Deployment in coastal regions west of Calvert 

I'm wondering if we should break apart this dataset in each component? @raytula any thoughts?

**Comment by pramod-thupaki** [comment]
I think we can keep the dataset together.

The location information could be 'Central Coast' or some other description of the broader region - this would be in keeping with the 'What, Where, When' recommended for CKAN records. 

You can mention, Quadra, Triquet, etc. in the description.

**Comment by raytula** [comment]
> I'm wondering if we should break apart this dataset in each component? @raytula any thoughts?

I suggest we keep it together.

**Comment by JessyBarrette** [comment]
Alright!

**Comment by JessyBarrette** [comment]
Dataset was added to production server!

**Comment by JessyBarrette** [comment]
Dataset and metadata records are now publicly available Hakai CKAN and ERDDAP, I would just need to have it available on the other CIOOS CKAN. @fostermh would make this specific  Hakai CKAN record available on the other CKAN?
https://catalogue.hakai.org/dataset/ca-cioos_87a845e3-e71a-43cc-a75f-ec6a3b812a0e

**Comment by JessyBarrette** [comment]
This dataset is now fully available on CKANs and ERDDAP. The CKAN link to ERDDAP wasn't showing the right server. This was updated and should be reflected tomorrow,
