### ISSUE TITLE
BamfieldBoL remote station new dataset

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#155]
## CIOOS Pacific Dataset Submission
This github issue present the different steps associated with the creation of a Hakai Institute ERDDAP dataset.

*Related links:*
- [x] Development ERDDAP Dataset: https://goose.hakai.org/erddap/tabledap/HakaiBamfieldBoL5min.html
- [x] [CIOOS Pacific Metadata Form](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-NdH-jgHZQzKrYdb2nw_)
- [x] CIOOS Pacific Catalogue:
- [x] Production ERDDAP Dataset: https://catalogue.hakai.org/erddap/tabledap/HakaiBamfieldBoL5min.html
--------

### Initial Submission
- [x] Original Data Source is available
- [x] CIOOS Metadata Form is completed

### ERDDAP Dataset Creation (Data Integrator)
- [x] Dataset Transformation
- [x] Near Real-time Data Integration
- [x] QARTOD Integration
- [x] ERDDAP Integration
- [x] ERDDAP Dataset Documentation
- [x] ERDDAP tested locally
- [x] Add Dataset to Development Branch
- [x] ERDDAP Global Attributes are matching the Metadata Record associated fields (see Metadata Form ERDDAP Snippet)

### Related Issues
List any issues related to this dataset submission that need to be reviewed prior to the submission.
- [x] Station positions lat/long?
- [x] Station pumping depth
- [x] Metadata record
- [x] show just the last 60days? yes!

### Dataset Approuval
The dataset provider needs to approve the dataset present within the CIOOS Pacific ERDDAP development server prior to making it available in production.
- [x] Development Dataset approved

-----
### Dataset Deployment in Production
This section lists the different steps needed to make an ERDDPAP dataset available in production.

#### ERDDAP
- [x] Merge Development  ERDDAP Dataset to Production Branch
- [x] Confirm ERDDAP Dataset is running on [CIOOS Pacific Production ERDDAP Server](https://data.cioospacific.ca/erddap/index.html)
#### Metadata Record
- [x] Confirm Metadata Record is pointing to the Production ERDDAP dataset
- [x] Publish Metadata record
- [x] Confirm Metadata record is available appropriately on the [CIOOS Pacific](https://catalogue.cioospacific.ca/dataset)
- [x] Confirm Metadata record is available appropriately on the [CIOOS National](https://catalogue.cioos.ca/dataset)

### DOI
- [x] Generate DOI associated with CIOOS Pacific CKAN dataset page?
- [x] COMPLETED

**Comment by JessyBarrette** [comment]
This is related to https://github.com/HakaiInstitute/hakai-sensor-network/issues/82

The new dataset is now available on the development server:
https://goose.hakai.org/erddap/tabledap/HakaiNovaBoL5min.html

@raytula The only missing pieces to get this dataset sorted that I can think of now are:
- metadata record
- lat/long of the actual location
- pumping depth?
- are we showing just the last 60days like the previous BoL?

**Comment by raytula** [comment]
Re: show just the last 60days?
Yes. However, I recently updated the back-end to only store recent data for all BoLs except Quadra, so you may not need to constrain your query --- but could do so just in case that changes.

**Comment by JessyBarrette** [comment]
ok easier to leave it there now and since all the other realtime BoL views have a 60days limit. I'll leave it there for consistency.

**Comment by raytula** [comment]
As per changes made https://github.com/HakaiInstitute/hakai-sensor-network/issues/82 the underlying SN naming has been updated to move from NovaBoL to BamfieldBoL.  The origial NovaBoL database tables will continue to exist for a while but new data will only be added to the BamfieldBoL database tables starting today.

**Comment by JessyBarrette** [comment]
The Bamfield dataset is now available online  We can now close this issue !!!
