### ISSUE TITLE
Decide which repo will be base repo for Hakai Data Mob. tasks and issues

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/hakai-datasets#157]
Should we use this hakai-datasets repo to house all the general to do items for the Hakai Data Mobilization team? Or should we create another repo specifically for Data Mobiliization issues and random code etc? It might be nice to have our own repo so we can set custom tags for issues. @JessyBarrette @timvdstap?

**Comment by JessyBarrette** [comment]
I think a whole new repo would make sense. Hakai dataset is for erddaps
stuff. I could rename it

Le ven. 1 sept. 2023 6:12 p.m., Brett Johnson ***@***.***> a
écrit :

**Comment by Br-Johnson** [comment]
I'm down with just creating a whole new repo for general data mobilization tasks/issues. Would be good to keep this datasets repo separate and specific to erddap datasets

**Comment by JessyBarrette** [comment]
Hakai-data?

Le ven. 1 sept. 2023 6:34 p.m., Brett Johnson ***@***.***> a
écrit :

**Comment by Br-Johnson** [comment]
Works for me.

B

**Comment by Br-Johnson** [comment]
see [hakaiinstitute/hakai-data](https://github.com/hakaiinstitute/hakai-data)
