### ISSUE TITLE
Dataset_ID: Hakai*[Provisional/Research/Climate] Test

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#2]
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [x] Raw Data Submission
- [x] CIOOS Metadata Form 

## ERDDAP Dataset Creation (Data Integrator)
- Dataset Transformation 
    - [x] :green_circle: Directly Compatible
    - [ ] :yellow_circle: Minor Revisions
    - [ ] :orange_circle: Major Revisions
    - [ ] :red_circle:  Incompatible/Missing Information
- [x] Near Real-time Data Integration 
    - [ ] :heavy_exclamation_mark: Required
- [x] QARTOD Integration 
    - [ ] :heavy_exclamation_mark: Required
- [x] ERDDAP Integration 
- [x] ERDDAP Dataset Documentation 
- [x] ERDDAP Test Locally 
- [x] Add Dataset to Development Branch
## Dataset Review (Data Administrator)
Dataset Development Branch Revision 
- [x] :green_circle: Approved
- [ ] :yellow_circle: Minor Revisions
- [ ] :orange_circle: Major Revisions

## Dataset Completion (Data Integrator)
- [x] Merge Development Dataset to Production Branch 
- [x] COMPLETED

**Comment by raytula** [comment]
> I think that I can comment now?

You sure can @jenjax2 !
