### ISSUE TITLE
Dataset Submission: Synthesized Nutrient Dataset associated with research paper by Hayley Dosser

### ISSUE THREAD

**Issue by raytula** [HakaiInstitute/hakai-datasets#64]
# Hakai Dataset Submission 

The intention of this issue is to make a nutrient dataset created and used by Hayley as part of a research paper Findable and Accessible via the Hakai metadata catalogue.   Similar to other synthesized/paper specific datasets, this dataset included data from multiple sources that has been aggregated and processed in ways specific a particular research project/paper.

Related examples include:

- [Hakai Oceanography Nutrient Research Dataset](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-Ma5RGdWbo_pLXJX3Sbg) (DRAFT, not yet published)
- [Marine CO2 system variability along the Inside Passage of the Pacific Northwest coast of North America determined from an Alaskan ferry](https://catalogue.hakai.org/dataset/ca-cioos_0e9e7d85-5378-4295-a38c-fb79b09609d9).  This dataset is specific to a research paper by Wiley and is referenced by this DOI: https://doi.org/10.21966/m0es-7520

Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [x] Draft a metadata record using the [Hakai metadata entry form](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai)

##  Online Dataset Creation (Data Integrator)
- [x] Make data files and extra information available in a new GitHub repository or open Google Drive Folder

## Dataset Review (Data Administrator)
- [x] Review data and metadata and approve for publishing

## Dataset Completion (Data Integrator)
- [ ] COMPLETED

**Comment by JessyBarrette** [comment]
@hvdosser Hi Hayley! 
I hope things are going well for you! Let me know if you have any questions regarding any of the points given by Ray above. I can help you get all this sorted out!

Best regards, 
Jessy

**Comment by timvdstap** [comment]
Hi Hayley!

I'll echo @JessyBarrette - happy to help where I can!

Cheers, Tim

**Comment by jenjax2** [comment]
Hi @hvdosser and @JessyBarrette 
After talking to @raytula, it seems like making one large synthesis product of all of the data you used (DFO and Hakai both CTD and nutrients) may make the most sense.

**Comment by JessyBarrette** [comment]
Hayley's Hakai Nutrient data is now available within this repository:
https://github.com/HakaiInstitute/Dosser-et-al2021-hakai-nutrient-dataset

**Comment by JessyBarrette** [comment]
The metedata records for Hayley et al. 2021 paper is available here:
https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/oOseiEWez6TzqPUIisEXczg6G8y2/-MoZtzH-n9LBy9Bn29Hl

I'm wondering about the paper's coauthor, Should they also be added to the contact list. @jenjax2 @raytula let me know your thoughts.

**Comment by raytula** [comment]
Re: _I'm wondering about the paper's coauthor, Should they also be added to the contact list._ 
Only if they were involved in preparing the dataset

**Comment by JessyBarrette** [comment]
@hvdosser a DOI is now available for you dataset :  https://doi.org/10.21966/j3j5-wt70

I updated the metadata form to include it should be available on the CKAN record itself by tomorrow.

**Comment by hvdosser** [comment]
Hi Jessy,

Thank you, that's great!

Hayley

**Comment by JessyBarrette** [comment]
I will close this issue since the dataset, metadata record and DOI are now all available!
