### ISSUE TITLE
Dataset Submission: HakaiCTDProvisional

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#7]
# Hakai Dataset Submission 
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [x] Original Data Submission
- [x] CIOOS Metadata Form completed

## ERDDAP Dataset Creation (Data Integrator)
- [x] Dataset Transformation  (Format label)
    - :green_circle: Format Compatible 
    - :yellow_circle: Format Minor Revisions
    - :orange_circle: Format Major Revisions
    - :red_circle:  Format Incompatible/Missing Information
- [x] Near Real-time Data Integration 
- [x] QARTOD Integration 
- [x] ERDDAP Integration 
- [x] ERDDAP Dataset Documentation 
- [x] ERDDAP Test Locally 
- [x] Add Dataset to Development Branch

## Dataset Review (Data Administrator)
*[ ERDDAP dev](https://goose.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileProvisional.html)
- [x] Dataset Development Branch Revision (Reviewer Label)
    - :green_circle: Reviewer Approved
    - :yellow_circle: Reviewer Minor Revisions    
    - :orange_circle: Reviewer Major Revisions

## Dataset Completion (Data Integrator)
- [x] Merge Development Dataset to Production Branch 
- [x] COMPLETED

**Comment by JessyBarrette** [comment]
@raytula  @jenjax2 @trollpete CIOOS Metadata form first draft for the CTD provisional dataset is now available here:
https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/review/hM2aN3v9MzZ6J4KGMOEW2s9gidj2/-MMHJ4k2EEwxkbXkrjxa

Based on Nate's comment's you won't be able to modify it but let me know we can change a lot of things. 
The CTD Research Dataset would likley have a very similar form with minor changes to it.

**Comment by JessyBarrette** [comment]
@jenjax2 @raytula @trollpete A first draft of the Hakai Water Properties Procedure manual is now available here:
https://docs.google.com/document/d/1C3oXnIvVgFEaoxNfHfArjNHYbHiIIbs325_R5nVnMLQ/edit?usp=sharing

**Comment by raytula** [comment]
> @raytula @jenjax2 @trollpete CIOOS Metadata form first draft for the CTD provisional dataset is now available here:
> https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/review/hM2aN3v9MzZ6J4KGMOEW2s9gidj2/-MMHJ4k2EEwxkbXkrjxa
> 
> Based on Nate's comment's you won't be able to modify it but let me know we can change a lot of things.
> The CTD Research Dataset would likley have a very similar form with minor changes to it.

I like it

**Comment by raytula** [comment]
> @jenjax2 @raytula @trollpete A first draft of the Hakai Water Properties Procedure manual is now available here:
> https://docs.google.com/document/d/1C3oXnIvVgFEaoxNfHfArjNHYbHiIIbs325_R5nVnMLQ/edit?usp=sharing

I like this too

**Comment by JessyBarrette** [comment]
@raytula @jenjax2 The provisional CTD Profile dataset is now available on Goose ERDDAP
https://goose.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileProvisional.html

We temporarily moved away from the database, the dataset is as of now served by generated netcdf files. All this will be move to the Hakai database once ready.

**Comment by JessyBarrette** [comment]
FYI it takes about 3h to run the tests on all the data. this include download the data and run tests, it should likely be much faster once done on the server side

**Comment by JessyBarrette** [comment]
CIOOS Metadata record, and ERDDAP datasets are now available on the productions sites

**Comment by raytula** [comment]
Great.  Thanks!

**Comment by JessyBarrette** [comment]
This dataset is now available online. We can close that issue!

**Comment by JessyBarrette** [comment]
This dataset is now available online. We can close that issue!
