### ISSUE TITLE
Dataset Submission: Hakai Dataset Submission template

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#85]
# Hakai Dataset Submission 
Below are listed all the different steps related to the initial submission of a dataset. 

A more detailed written and visual description of every step is available respectively 
[here](https://docs.google.com/document/d/1QMU0skj7kWbxuS_cVUNkTYZSeqpa1lVsK7WJvC4hMyA/edit?usp=sharing) and [here](https://lucid.app/lucidchart/invitations/accept/ae8530a5-4a8f-435e-b17a-60aab0773f2f). 

# Submission steps
## Initial Submission (Data Administrator)
- [ ] Original Data Submission
- [ ] CIOOS Metadata Form completed

## ERDDAP Dataset Creation (Data Integrator)
- [ ] Dataset Transformation  (Format label)
    - :green_circle: Format Compatible 
    - :yellow_circle: Format Minor Revisions
    - :orange_circle: Format Major Revisions
    - :red_circle:  Format Incompatible/Missing Information
- [ ] Near Real-time Data Integration 
- [ ] QARTOD Integration 
- [ ] ERDDAP Integration 
- [ ] ERDDAP Dataset Documentation 
- [ ] ERDDAP Test Locally 
- [ ] Add Dataset to Development Branch
- [ ] ERDDAP Global Attributes are matching the Metadata Record associated fields (see Metadata Form ERDDAP Snippet) 

## Dataset Review (Data Administrator)
- [ ] Dataset Development Branch Revision (Reviewer Label)
    - :green_circle: Reviewer Approved
    - :yellow_circle: Reviewer Minor Revisions    
    - :orange_circle: Reviewer Major Revisions

### ERDDAP
- [ ] Merge Development  ERDDAP Dataset to Production Branch 
- [ ] Confirm ERDDAP Dataset is running on [Hakai Production ERDDAP Server](https://catalogue.hakai.org/erddap/index.html)
### Metadata Record
- [ ] Confirm Metadata Record is pointing to the Production ERDDAP dataset
- [ ] Publish Metadata record
- [ ] Confirm Metadata record is available appropriately on the [Hakai Institute CKAN](https://catalogue.hakai.org/dataset)
- [ ] Confirm Metadata record is available appropriately on the [CIOOS Pacific](https://catalogue.cioospacific.ca/dataset)
- [ ] Confirm Metadata record is available appropriately on the [CIOOS National](https://catalogue.cioos.ca/dataset)

## DOI
- [ ] Generate DOI associated with Hakai CKAN dataset page

- [ ] COMPLETED

**Comment by JessyBarrette** [comment]
@Br-Johnson @timvdstap @pramod-thupaki You can find above the latest version of the Dataset submission template used with to track the submission process of each datasets. 

Have a look and let me know if there's any changes you would like to see in there.

**Comment by Br-Johnson** [comment]
I assume this would be the template issue that would be created when a metadata record is submitted? If so, this template is very focussed on ERDDAP. There might need to be more general checks for data that are only going to be available as data packages. For example: Data package includes: Readme file, Changelog, plain text files etc... Also will the default checklist be focussed for the program data manager/PI or for the Hakai Data Stewards?

We have a review checklist going https://docs.google.com/document/d/1BYUnaaII-nVPiOym__Ag-Pf-wIIj4PlRVg7dFaGbArk/edit
