### ISSUE TITLE
Update: Hakai Rivers Inlet Mooring dataset

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#91]
# TO DO
Include the latest data from the Rivers Inlet mooring dataset. 
- [x] Change the data workflow to a full a github repo method like other datasets
- [x] Update the processing method to handle the ocean_data_parser package
- [x] QC data
- [x] Make data available on dev erddap
- [x] Confirm data with Jen
- [x] Make data available on production
- [x] Confirm Metadata record is correct

**Comment by JessyBarrette** [comment]
The new repository https://github.com/HakaiInstitute/hakai-rivers-inlet-mooring is now the newest location where the data is stored and processed. Pictures of the mooring will remain on the google Drive.

**Comment by JessyBarrette** [comment]
Hi @jenjax2, the latest Rivers Inlet Mooring data is now available on our development ERDDAP for revision from you.

You can access the data here:
https://goose.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.html

Here's some quick figures of the data
![image](https://user-images.githubusercontent.com/30420025/181769181-a637e06b-294f-48d8-83ac-26b816039db3.png)
![image](https://user-images.githubusercontent.com/30420025/181769221-470caa88-058f-4bec-8575-9a590c249b63.png)
![image](https://user-images.githubusercontent.com/30420025/181769283-919d0414-15bf-43a7-976c-7b214c1601cb.png)

**Comment by JessyBarrette** [comment]
Hi @chrishakai, I would like to confirm with you that the CTDs deployed  at the last deployment of the Rivers Inlet mooring were sync to UTC time. Could you confirm that? And I'm wondering if you did do a clock check after the deployment to asses the clock drift of each instruments?

**Comment by JessyBarrette** [comment]
Comparison with the CTD data collected over the deployment are also in great agreement!
## 100m data
![rivers100m](https://user-images.githubusercontent.com/30420025/181799407-d89bd88c-2730-466b-a7ac-b788268600d1.png)
## 250m data
![rivers250m](https://user-images.githubusercontent.com/30420025/181799347-783cf09c-3b90-4869-bdc5-56bdf81dc628.png)

**Comment by JessyBarrette** [comment]
notebook used to generate those plots can be found here:
https://github.com/HakaiInstitute/hakai-rivers-inlet-mooring/blob/d714f2786292fa4cf4c9706749cb6a515afc8de1/review_rivers_inlet_mooring_2022.ipynb

**Comment by jenjax2** [comment]
Thanks @JessyBarrette for putting these data together! It looks like our moored oxygen and salinity sensors were lower than the profile data for thee deep sensor. Any idea what may have caused the offset?

**Comment by JessyBarrette** [comment]
Yeah sorry it's a bit confusing, the package I'm using to make those plots didnt want to put the dots in front of the lines. Basically, the further away records you see from the 250m mooring data is from the DFO2 mooring. DFO3 is closer to the line if not on it.

See the pink dot in oxygen which is from DFO3. 
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/30420025/184232883-edd4d7cc-f466-40c3-a8a2-6f3ad8713509.png">

The difference observed between the mooring and ctd at DFO3 in salinity is of about 0.008 which is getting close to our accuracy I would think.

**Comment by JessyBarrette** [comment]
Hi @jenjax2, are you ok with me making the latest Rivers Inlet data available online?

**Comment by jenjax2** [comment]
Hi @JessyBarrette yes it looks good to me. These data can now go online. Thanks!!

**Comment by JessyBarrette** [comment]
Awesome thanks!

**Comment by JessyBarrette** [comment]
The latest data is now available on production ERDDAP
https://catalogue.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.graph?time%2CTEMPS901%2Cdepth&.draw=markers&.marker=5%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff
