### ISSUE TITLE
Add non public datasets to hakai ERDDAP

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#93]
# General idea
As Hakai starts to use more and more ERDDAP has a primary platform to share and make accessible data. We're hoping to provide access to some of our data to our different internal Hakai groups through some **non-public** ERDDAP datasets. (see #92  as a first example)

Those datasets will be generated to help the different Hakai groups to get access to their data, access the data quality and problems, and eventually either make this specific dataset available or create another data product that will be made available.

# Solutions
ERDDAP provides the ability to keep some datasets behind an authentication wall ([see here for documentation](https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#security)). A number of methods can be used to authenticate. Among those the most interesting are:
1. custom -> username password
2. google
3. 2Oauth

# Conditions
The method used needs to be:
- Secure 
- Easy to handle through the API with through different packages that will need to be developed to retrieve the protected data (matlab,python,...)

# Steps
- [ ] Which method should be used
- [ ] Add OA as a role
- [ ] Confirm that the authentication method still makes it possible to retrieve the data through a MatLab script.

**Comment by n-a-t-e** [comment]
We could do that, another option would be to stick it on goose ERDDAP which is already protected - http://goose.hakai.org/erddap

**Comment by JessyBarrette** [comment]
We've decided to maintain for now any non public datasets within on dev server only for now
